version: "3.9"
services:
  next-chatbot:
    image: postgres
    restart: always
    container_name: next-chatbot
    ports:
      - 5439:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
